package com.example.jpastart.controller;

import com.example.jpastart.model.Student;
import com.example.jpastart.repository.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;

@RestController
public class StudentRestController {

    @Autowired
    StudentRepository studentRepository;

    @GetMapping("/students")
    public List<Student> students() {
        List<Student> lst = studentRepository.findAll();
        return lst;
    }

    @GetMapping("/addStudent")
    public List<Student> addStudent() {
        Student student = new Student();
        student.setBorn(LocalDate.now());
        student.setBornTime(LocalTime.now());
        List<Student> list = studentRepository.findAll();
        student.setName("Autogenerated size : " + list.size());
        studentRepository.save(student);
        return list;
    }
}
